# Generated by Django 2.2.1 on 2019-10-21 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(default='Web Developer', max_length=200)),
                ('avater', models.ImageField(null=True, upload_to='avater')),
                ('about', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JAVASCRIPT', 'JAVASCRIPT'), ('PYTHON', 'PYTHON'), ('DJANGO', 'DJANGO'), ('WORDPRESS', 'WORDPRESS'), ('PHP', 'PHP')], max_length=50)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.Freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(null=True, upload_to='portfolio_image')),
                ('about', models.TextField(blank=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='main.Freelancer')),
            ],
        ),
    ]
