# Generated by Django 2.2.1 on 2019-10-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
